### ISSUE TITLE
Suggestion: use dired-mark-if macro in dired-mark-empty-dirs

### ISSUE THREAD

**Issue by oantolin** [amno1/.emacs.d#1]
I couldn't figure out how to leave a comment on your blog, so I'm doing it here. I think your `dired-mark-empty-dirs` function would look nicer if you use the `dired-mark-if` macro:

```elisp
(defun dired-mark-empty-directories (&optional arg)
  "Mark empty directories.
A prefix argument means to unmark them instead."
  (interactive "P")
  (let ((dired-marker-char (if arg ?\s dired-marker-char)))
    (dired-mark-if
     (when-let ((dir (dired-get-filename t t)))
       (directory-is-empty-p dir))
     "empty directory")))
```

There is one disadvantage: the string argument, "empty directory" in this case, is pluralized by blindly adding an "s". You may prefer to pass the string "empty directorie". 😆

**Comment by amno1** [comment]
Thank you! Yes indeed, that one was really handcrafted :-). Dired is such a forest of useful stuff, but I rarely look at what is there. That is my bad habits showing up: I just code :).

People have left me comments on the blog which I approved, but they never show up. Don't know if it is Wordpress or the theme. Tried to fix it but never got it to work. Had plans to replace WP with static site, possibly some org generator, but never got to it.

**Comment by amno1** [comment]
I have finally pulled the thumb out of my a*s and updated the blog, thanks for the suggestion! If you want me to link elsewhere than your gh repos, let me know.

http://www.nextpoint.se/?p=808

**Comment by oantolin** [comment]
The GitHub link is fine, thanks. If you don't mind, could you change the name to "Omar Antolín Camarena"? Antolín is not a middle name, it's my paternal surname (and Camarena is my maternal surname). It's not a big deal and I am pretty used to people omitting "Antolín".

**Comment by amno1** [comment]
Sure, fixed :-)
